services:
  - type: web
    name: diabetes-predictor
    env: docker
    plan: free
    repo: https://github.com/lebadac/Diabetes_Project
    branch: main
    dockerfilePath: server/Dockerfile
    buildFilter:
      paths:
        - server/**
    envVars:
      - key: PORT
        value: 8888
